from __future__ import annotations

from pathlib import Path

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.common.ids import new_id
from app.common.json import json_safe
from app.core.exceptions import NotFoundException
from app.modules.learning_paths.models import (
    LearningAnswer,
    LearningPath,
    LearningTask,
    PathReport,
    ReportRecord,
)
from app.modules.learning_paths.rules import build_path
from app.modules.profiles.service import (
    _record_history,
    profile_data,
    profile_dimensions,
    require_profile,
    weak_points,
)
from app.modules.learning_paths.word_reports import safe_filename, write_docx
from app.modules.recognition.models import RecognitionRecord
from app.modules.tasks.models import TaskRecord


async def update_path(
    session: AsyncSession, learner_id: str, reason: str = "manual_update"
) -> LearningPath:
    await require_profile(session, learner_id)
    dimensions = await profile_dimensions(session, learner_id)
    average = (
        sum(item["score"] for item in dimensions) / len(dimensions)
        if dimensions
        else 0.0
    )
    recent_answers = list(
        (
            await session.scalars(
                select(LearningAnswer)
                .where(LearningAnswer.learner_id == learner_id)
                .order_by(LearningAnswer.id.desc())
                .limit(2)
            )
        ).all()
    )
    consecutive_errors = (
        2
        if len(recent_answers) == 2
        and all(not answer.is_correct for answer in recent_answers)
        and recent_answers[0].knowledge_point == recent_answers[1].knowledge_point
        else 0
    )
    current = await session.scalar(
        select(LearningPath)
        .where(LearningPath.learner_id == learner_id)
        .order_by(LearningPath.version.desc())
    )
    version = (current.version if current else 0) + 1
    result = build_path(average, consecutive_errors)
    item = LearningPath(
        learner_id=learner_id,
        version=version,
        status="active",
        current_stage=result["current_stage"],
        path_json=result,
        reason=reason,
    )
    session.add(item)
    for task_type in result["recommended_task_types"]:
        session.add(
            LearningTask(
                learning_task_id=new_id("learn"),
                learner_id=learner_id,
                task_type=task_type,
                title=f"Recommended {task_type.replace('_', ' ')}",
                description="Generated by deterministic V0.2 learning-path rules.",
                difficulty=(
                    "basic"
                    if result["current_stage"] == "foundation"
                    else "advanced"
                    if result["current_stage"] == "advanced"
                    else "intermediate"
                ),
                status="recommended",
                recommended_reason=reason,
            )
        )
    await _record_history(
        session,
        learner_id,
        "learning_path_updated",
        {"version": current.version} if current else None,
        {"version": version, "path": result},
        reason,
    )
    await session.commit()
    await session.refresh(item)
    return item


def path_data(item: LearningPath) -> dict:
    return {
        "learner_id": item.learner_id,
        "version": item.version,
        "status": item.status,
        "current_stage": item.current_stage,
        "path": item.path_json,
        "reason": item.reason,
        "created_at": item.created_at,
        "updated_at": item.updated_at,
    }


async def latest_path(session: AsyncSession, learner_id: str) -> LearningPath:
    item = await session.scalar(
        select(LearningPath)
        .where(LearningPath.learner_id == learner_id)
        .order_by(LearningPath.version.desc())
    )
    if item is None:
        raise NotFoundException("Learning path not found")
    return item


async def generate_learning_report(
    session: AsyncSession, learner_id: str
) -> ReportRecord:
    profile = await require_profile(session, learner_id)
    path = await latest_path(session, learner_id)
    record = ReportRecord(
        report_id=new_id("report"),
        learner_id=learner_id,
        report_type="learning",
        title="Mock learning report",
        content_json=json_safe(
            {
                "data_source": "mock",
                "is_official": False,
                "profile": profile_data(profile),
                "weak_points": await weak_points(session, learner_id),
                "path": path_data(path),
            }
        ),
        status="generated",
    )
    session.add(record)
    session.add(
        PathReport(
            report_id=record.report_id,
            learner_id=learner_id,
            profile_snapshot_json=json_safe(profile_data(profile)),
            weak_points_json=json_safe(await weak_points(session, learner_id)),
            path_snapshot_json=json_safe(path_data(path)),
            summary="Mock learning-path report",
        )
    )
    await session.commit()
    await session.refresh(record)
    return record


def report_data(item: ReportRecord) -> dict:
    return {
        "report_id": item.report_id,
        "learner_id": item.learner_id,
        "report_type": item.report_type,
        "title": item.title,
        "content": item.content_json,
        "file_id": item.file_id,
        "download_available": bool(item.output_path),
        "status": item.status,
        "created_at": item.created_at,
        "updated_at": item.updated_at,
    }


async def latest_learning_report(
    session: AsyncSession, learner_id: str
) -> ReportRecord:
    item = await session.scalar(
        select(ReportRecord)
        .where(
            ReportRecord.learner_id == learner_id,
            ReportRecord.report_type == "learning",
        )
        .order_by(ReportRecord.id.desc())
    )
    if item is None:
        raise NotFoundException("Learning report not found")
    return item


async def require_report(session: AsyncSession, report_id: str) -> ReportRecord:
    item = await session.scalar(
        select(ReportRecord).where(ReportRecord.report_id == report_id)
    )
    if item is None:
        raise NotFoundException("Report not found")
    return item


def _report_path(report_id: str) -> tuple[Path, str]:
    from app.core.config import get_settings

    root = get_settings().effective_report_dir().resolve()
    filename = safe_filename(report_id) + ".docx"
    target = (root / filename).resolve()
    if root not in target.parents:
        raise ValueError("Unsafe report path")
    return target, filename


async def export_learning_word(session: AsyncSession, learner_id: str) -> ReportRecord:
    report = await generate_learning_report(session, learner_id)
    content = report.content_json
    profile = content.get("profile", {})
    path = content.get("path", {})
    target, relative = _report_path(report.report_id)
    write_docx(
        target,
        "HerbWise-AI 学情报告",
        [
            f"报告编号：{report.report_id}",
            f"学习者：{learner_id}",
            "数据来源：" + str(content.get("data_source", "mock")),
            "说明：本报告用于学习反馈，不构成临床诊断或处方。",
            "学习画像：" + str(profile),
            "薄弱点：" + str(content.get("weak_points", [])),
            "学习路径：" + str(path),
        ],
    )
    report.output_path = relative
    report.title = "Learning report (Word)"
    await session.commit()
    await session.refresh(report)
    return report


async def export_recognition_word(session: AsyncSession, task_id: str) -> ReportRecord:
    task = await session.scalar(select(TaskRecord).where(TaskRecord.task_id == task_id))
    if task is None:
        raise NotFoundException("Task not found")
    recognition = await session.scalar(
        select(RecognitionRecord)
        .where(RecognitionRecord.task_id == task_id)
        .order_by(RecognitionRecord.id.desc())
    )
    target_id = new_id("report")
    target, relative = _report_path(target_id)
    data_source = recognition.data_source if recognition else "unknown"
    write_docx(
        target,
        "HerbWise-AI 识别审核报告",
        [
            f"报告编号：{target_id}",
            f"任务：{task_id}",
            f"学习者：{task.learner_id}",
            f"最终识别：{recognition.final_name if recognition else '未生成'}",
            f"置信度：{recognition.confidence if recognition else 'N/A'}",
            f"人工复核：{recognition.manual_review_required if recognition else True}",
            f"数据来源：{data_source}",
            "说明：识别结果仅用于教学演示，不构成临床诊断或处方。",
        ],
    )
    report = ReportRecord(
        report_id=target_id,
        learner_id=task.learner_id,
        report_type="recognition_review",
        title="Recognition review report (Word)",
        content_json={
            "task_id": task_id,
            "data_source": data_source,
            "recognition_id": recognition.recognition_id if recognition else None,
        },
        status="generated",
        output_path=relative,
    )
    session.add(report)
    await session.commit()
    await session.refresh(report)
    return report


def report_file_path(report: ReportRecord) -> Path:
    if not report.output_path:
        raise NotFoundException("Report file not found")
    from app.core.config import get_settings

    root = get_settings().effective_report_dir().resolve()
    candidate = (root / report.output_path).resolve()
    if root not in candidate.parents or not candidate.is_file():
        raise NotFoundException("Report file not found")
    return candidate


async def create_learning_answer(
    session: AsyncSession,
    *,
    learner_id: str,
    task_id: str | None,
    question_id: int | None,
    dimension_code: str,
    knowledge_point: str,
    answer: dict,
    is_correct: bool,
    score: float,
    feedback: str | None,
) -> LearningAnswer:
    await require_profile(session, learner_id)
    item = LearningAnswer(
        learner_id=learner_id,
        task_id=task_id,
        question_id=question_id,
        dimension_code=dimension_code,
        knowledge_point=knowledge_point,
        answer_json=answer,
        is_correct=is_correct,
        score=score,
        feedback=feedback,
    )
    session.add(item)
    await session.commit()
    await session.refresh(item)
    return item


def answer_data(item: LearningAnswer) -> dict:
    return {
        "id": item.id,
        "learner_id": item.learner_id,
        "task_id": item.task_id,
        "question_id": item.question_id,
        "dimension_code": item.dimension_code,
        "knowledge_point": item.knowledge_point,
        "answer": item.answer_json,
        "is_correct": item.is_correct,
        "score": item.score,
        "feedback": item.feedback,
        "submitted_at": item.submitted_at,
    }


async def list_learning_answers(
    session: AsyncSession, learner_id: str, page: int, page_size: int
) -> dict:
    await require_profile(session, learner_id)
    total = (
        await session.scalar(
            select(func.count())
            .select_from(LearningAnswer)
            .where(LearningAnswer.learner_id == learner_id)
        )
        or 0
    )
    records = list(
        (
            await session.scalars(
                select(LearningAnswer)
                .where(LearningAnswer.learner_id == learner_id)
                .order_by(LearningAnswer.id.desc())
                .offset((page - 1) * page_size)
                .limit(page_size)
            )
        ).all()
    )
    return {
        "items": [answer_data(item) for item in records],
        "page": page,
        "page_size": page_size,
        "total": total,
        "pages": (total + page_size - 1) // page_size,
    }
